/*
  Warnings:

  - You are about to drop the column `description` on the `Boat` table. All the data in the column will be lost.
  - You are about to drop the column `lengthFeet` on the `Boat` table. All the data in the column will be lost.
  - You are about to drop the column `make` on the `Boat` table. All the data in the column will be lost.
  - You are about to drop the column `model` on the `Boat` table. All the data in the column will be lost.
  - You are about to drop the column `price` on the `Boat` table. All the data in the column will be lost.
  - You are about to drop the column `title` on the `Boat` table. All the data in the column will be lost.
  - Added the required column `cost` to the `Boat` table without a default value. This is not possible if the table is not empty.
  - Added the required column `name` to the `Boat` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE `Boat` DROP COLUMN `description`,
    DROP COLUMN `lengthFeet`,
    DROP COLUMN `make`,
    DROP COLUMN `model`,
    DROP COLUMN `price`,
    DROP COLUMN `title`,
    ADD COLUMN `alternator` VARCHAR(191) NULL,
    ADD COLUMN `anodes` VARCHAR(191) NULL,
    ADD COLUMN `appliances` VARCHAR(191) NULL,
    ADD COLUMN `ballast` VARCHAR(191) NULL,
    ADD COLUMN `bathroomBathShower` VARCHAR(191) NULL,
    ADD COLUMN `bathroomExtraNotes` VARCHAR(191) NULL,
    ADD COLUMN `bathroomLength` VARCHAR(191) NULL,
    ADD COLUMN `bathroomToilet` VARCHAR(191) NULL,
    ADD COLUMN `bathroomVanityBasin` VARCHAR(191) NULL,
    ADD COLUMN `bathroomWasteTankCapacity` VARCHAR(191) NULL,
    ADD COLUMN `batteries` VARCHAR(191) NULL,
    ADD COLUMN `bedroomBed` VARCHAR(191) NULL,
    ADD COLUMN `bedroomDinette` VARCHAR(191) NULL,
    ADD COLUMN `bedroomExtraNotes` VARCHAR(191) NULL,
    ADD COLUMN `bedroomLength` VARCHAR(191) NULL,
    ADD COLUMN `blacking` VARCHAR(191) NULL,
    ADD COLUMN `boatName` VARCHAR(191) NULL,
    ADD COLUMN `boatSafety` VARCHAR(191) NULL,
    ADD COLUMN `boilerServiceHistory` VARCHAR(191) NULL,
    ADD COLUMN `bowthruster` VARCHAR(191) NULL,
    ADD COLUMN `builder` VARCHAR(191) NULL,
    ADD COLUMN `cabinSides` VARCHAR(191) NULL,
    ADD COLUMN `ceiling` VARCHAR(191) NULL,
    ADD COLUMN `centralHeating` VARCHAR(191) NULL,
    ADD COLUMN `cinNumber` VARCHAR(191) NULL,
    ADD COLUMN `cost` VARCHAR(191) NOT NULL,
    ADD COLUMN `covers` VARCHAR(191) NULL,
    ADD COLUMN `crtNumber` VARCHAR(191) NULL,
    ADD COLUMN `dieselTankCapacity` VARCHAR(191) NULL,
    ADD COLUMN `documentationAvailable` VARCHAR(191) NULL,
    ADD COLUMN `draft` VARCHAR(191) NULL,
    ADD COLUMN `electricalExtraNotes` VARCHAR(191) NULL,
    ADD COLUMN `engine` VARCHAR(191) NULL,
    ADD COLUMN `engineExtraNotes` VARCHAR(191) NULL,
    ADD COLUMN `engineServiceHistory` VARCHAR(191) NULL,
    ADD COLUMN `fitOut` VARCHAR(191) NULL,
    ADD COLUMN `flooring` VARCHAR(191) NULL,
    ADD COLUMN `galleyCooker` VARCHAR(191) NULL,
    ADD COLUMN `galleyExtraNotes` VARCHAR(191) NULL,
    ADD COLUMN `galleyFridgeFreezer` VARCHAR(191) NULL,
    ADD COLUMN `galleyLength` VARCHAR(191) NULL,
    ADD COLUMN `galleyMicrowave` VARCHAR(191) NULL,
    ADD COLUMN `galleyWashingMachine` VARCHAR(191) NULL,
    ADD COLUMN `galvanicIsolator` VARCHAR(191) NULL,
    ADD COLUMN `gasBottles` VARCHAR(191) NULL,
    ADD COLUMN `gearbox` VARCHAR(191) NULL,
    ADD COLUMN `heatingExtraNotes` VARCHAR(191) NULL,
    ADD COLUMN `hours` VARCHAR(191) NULL,
    ADD COLUMN `hullBuilder` VARCHAR(191) NULL,
    ADD COLUMN `hullSides` VARCHAR(191) NULL,
    ADD COLUMN `insulation` VARCHAR(191) NULL,
    ADD COLUMN `interiorExtraNotes` VARCHAR(191) NULL,
    ADD COLUMN `internalHeadroom` VARCHAR(191) NULL,
    ADD COLUMN `inverterCharger` VARCHAR(191) NULL,
    ADD COLUMN `landlineSocket` VARCHAR(191) NULL,
    ADD COLUMN `lastService` VARCHAR(191) NULL,
    ADD COLUMN `lengthBeam` VARCHAR(191) NULL,
    ADD COLUMN `licenseNumber` VARCHAR(191) NULL,
    ADD COLUMN `lighting` VARCHAR(191) NULL,
    ADD COLUMN `location` VARCHAR(191) NULL,
    ADD COLUMN `name` VARCHAR(191) NOT NULL,
    ADD COLUMN `navigationEquipment` VARCHAR(191) NULL,
    ADD COLUMN `noOfBerths` VARCHAR(191) NULL,
    ADD COLUMN `overview` TEXT NULL,
    ADD COLUMN `previousOwners` VARCHAR(191) NULL,
    ADD COLUMN `recentSurvey` VARCHAR(191) NULL,
    ADD COLUMN `saloonDinette` VARCHAR(191) NULL,
    ADD COLUMN `saloonLength` VARCHAR(191) NULL,
    ADD COLUMN `saloonSeating` VARCHAR(191) NULL,
    ADD COLUMN `sideDoors` VARCHAR(191) NULL,
    ADD COLUMN `solidFuelStove` VARCHAR(191) NULL,
    ADD COLUMN `sourceOfHotWater` VARCHAR(191) NULL,
    ADD COLUMN `steelSpec` VARCHAR(191) NULL,
    ADD COLUMN `sternType` VARCHAR(191) NULL,
    ADD COLUMN `survey` VARCHAR(191) NULL,
    ADD COLUMN `tv` VARCHAR(191) NULL,
    ADD COLUMN `waterTank` VARCHAR(191) NULL,
    ADD COLUMN `waterTankCapacity` VARCHAR(191) NULL,
    ADD COLUMN `weedhatch` VARCHAR(191) NULL,
    ADD COLUMN `windows` VARCHAR(191) NULL,
    ADD COLUMN `yearBuilt` VARCHAR(191) NULL,
    MODIFY `year` VARCHAR(191) NULL;
